all:
  hosts:
    neliub-k8s-master:
      ansible_host: 10.7.5.5
      ip: 10.7.5.5
      access_ip: 10.7.5.5
    neliub-k8s-worker-node-1:
      ansible_host: 10.7.5.6
      ip: 10.7.5.6
      access_ip: 10.7.5.6
    neliub-k8s-worker-node-2:
      ansible_host: 10.7.5.7
      ip: 10.7.5.7
      access_ip: 10.7.5.7

  children:
    kube_control_plane:
      hosts:
        neliub-k8s-master:
    kube_node:
      hosts:
        neliub-k8s-worker-node-1:
        neliub-k8s-worker-node-2:
    etcd:
      hosts:
        neliub-k8s-master:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
