apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-autscl
  namespace: argocd
  labels:
    enc: prod
    owner: neliub_ivan
spec:
  selector:
    project: {{ .Release.Name }}-autscl-prj #Selecting PODS with those Labels
  ports:
    - name: {{ .Release.Name }}-autoscaling      
      protocol: TCP
      port: 80 #Port on Load Balancer
      targetPort: 80 #Port on POD
  type: ClusterIP # Или LoadBalancer/NodePort, если нужно
