apiVersion: apps/v1
kind: Deployment
metadata:
  name: neliub-svc-test-autoscaling
  labels:
    app: neliub-svc-test-autoscaling
spec:
  selector:
    matchLabels:
      project: neliub-svc-autoscaling #Service will look for those PODS Labels
  template:
    metadata:
      labels:
        project: neliub-svc-autoscaling
    spec:
      containers:
         - name: svc-web-autoscaling
           image: nginx:latest
           ports:
             - containerPort: 80

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: neliub-svc-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: neliub-svc-autoscaling
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

---

apiVersion: v1
kind: Service
metadata:
  name: my-svc-neliub-autoscaling
  labels:
    enc: prod
    owner: neliub_ivan
spec:
  selector:
    project: neliub-svc-autoscaling #Selecting PODS with those Labels
  ports:
    - name: app-listener-autoscaling      
      protocol: TCP
      port: 80 #Port on Load Balancer
      targetPort: 80 #Port on POD
  type: ClusterIP # Или LoadBalancer/NodePort, если нужно
