apiVersion: apps/v1
kind: Deployment
metadata:
  name: neliub-svc-test
  labels:
    app: neliub-svc-test
spec:
  replicas: 3
  selector:
    matchLabels:
      project: neliub-svc #Service will look for those PODS Labels
  template:
    metadata:
      labels:
        project: neliub-svc
    spec:
      containers:
         - name: svc-web
           image: nginx:latest
           ports:
             - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-svc-neliub
  labels:
    enc: prod
    owner: neliub_ivan
spec:
  selector:
    project: neliub-svc #Selecting PODS with those Labels
  ports:
    - name: app-listener      
      protocol: TCP
      port: 80 #Port on Load Balancer
      targetPort: 80 #Port on POD
  type: ClusterIP # Или LoadBalancer/NodePort, если нужно
