apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-my-mysql-8
  labels:
    app: svc-my-mysql-8
spec:
  selector:
    matchLabels:
      project: svc-my-mysql-8 #Service will look for those PODS Labels
  template:
    metadata:
      labels:
        project: svc-my-mysql-8
    spec:
      containers:
         - name: my-mysql
           image: w1a2n3o4/mysql-8.0:latest
           ports:
             - containerPort: 3306

---

#apiVersion: autoscaling/v2
#kind: HorizontalPodAutoscaler
#metadata:
#  name: svc-my-mysql-8
#spec:
#  scaleTargetRef:
#    apiVersion: apps/v1
#    kind: Deployment
#    name: svc-my-mysql-8
#  minReplicas: 5
#  maxReplicas: 10
#  metrics:
#  - type: Resource
#    resource:
#      name: cpu
#      target:
#        type: Utilization
#        averageUtilization: 90
#  - type: Resource
#    resource:
#      name: memory
#      target:
#        type: Utilization
#        averageUtilization: 90

---

apiVersion: v1
kind: Service
metadata:
  name: svc-my-mysql-8
  labels:
    enc: prod
    owner: neliub_ivan
spec:
  selector:
    project: svc-my-mysql-8 #Selecting PODS with those Labels
  ports:
    - name: svc-my-mysql-8      
      protocol: TCP
      port: 3306 #Port on Load Balancer
      targetPort: 3306 #Port on POD
  type: ClusterIP # Или LoadBalancer/NodePort, если нужно
