apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-wordpress
  labels:
    app: svc-wordpress
spec:
  selector:
    matchLabels:
      project: svc-wordpress #Service will look for those PODS Labels
  template:
    metadata:
      labels:
        project: svc-wordpress
    spec:
      containers:
         - name: wordpress
           image: wordpress:php8.3-fpm-alpine
           ports:
             - containerPort: 80

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: svc-wordpress
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: svc-wordpress
  minReplicas: 5
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 95
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 95

---

apiVersion: v1
kind: Service
metadata:
  name: svc-wordpress
  labels:
    enc: prod
    owner: neliub_ivan
spec:
  selector:
    project: svc-wordpress #Selecting PODS with those Labels
  ports:
    - name: svc-wordpress      
      protocol: TCP
      port: 80 #Port on Load Balancer
      targetPort: 80 #Port on POD
  type: ClusterIP # Или LoadBalancer/NodePort, если нужно
