apiVersion: apps/v1
kind: Deployment
metadata:
  name: neliub-deploy-test
  labels:
    app : my-k8s-test
spec:
  selector:
    matchLabels:
      project: tst
  template:
    metadata:
      labels:
        project: tst
    spec:
      containers:
        - name : tst-web
          image: nginx:latest
          ports:
            - containerPort: 80
