apiVersion: apps/v1
kind: Deployment
metadata:
  name: neliub-deploy-test-autoscaling
  labels:
    app : my-k8s-test-autoscaling
    env : prod
    owner: ivan_neliub
spec:
  replicas: 5
  selector:
    matchLabels:
      project: as-rp
  template:
    metadata:
      labels:
        project: as-rp
    spec:
      containers:
        - name : my-k8s-app-v2
          image: w1a2n3o4/k8s-app-25-v2:latest
          ports:
            - containerPort: 80

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: neliub-deploy-test-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-autoscaling
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
