apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.7.5.10/32
  #- 10.7.6.5/32
  #- 10.200.200.100-10.200.200.120  # Замените на ваш диапазон IP
  autoAssign: true