apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb-system
spec:
  addresses:
  - 93.125.23.238/32
  #- 10.200.200.100-10.200.200.120  # Диапазон IP
  autoAssign: true