apiVersion: v1
kind: Pod
metadata:
  name: my-test
  labels:
    env   : prod
    app   : main
    tier  : frontend
    owner : ivan_neliub 
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
